version: '3.8'

services:
  app:
    build: .
    container_name: RHManager
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  db:
    image: postgres:13-alpine
    container_name: RHManager_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rhmanager_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
